name: Run Python Script

on:
  workflow_dispatch:
    inputs:
      script_name:
        description: "Nome dello script Python da eseguire"
        required: true
        default: "Dice rolling simulator.py"

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run selected Python script
        run: python "${{ github.event.inputs.script_name }}"
